<?php echo $this->doctype(); ?>
<html>
<head>
    <?php echo $this->headTitle();?>
    <?php echo $this->headMeta();?>
    <?php echo $this->headLink();?>
    <?php echo $this->headStyle();?>
    <?php echo $this->headScript();?>
    <?php echo $this->jQuery();?>
</head>
<body>
    <h1>Hello form layout: "<?php echo Zend_Layout::getMvcInstance()->getLayout();?>".</h1>
    <?php echo $this->layout()->content; ?>
</body>
</html>