<?php
$this->headLink()->appendStylesheet('/css/flexible-box.css');
echo $this->doctype(); 
?>
<html>
<head>    
    <?php echo $this->headTitle();?>
    <?php echo $this->headMeta();?>
    <?php echo $this->headLink();?>
    <?php echo $this->headStyle();?>
    <?php echo $this->headScript();?>
    <?php echo $this->jQuery();?>
</head>
<body>
    <header>
        <a href="/">Responsive Web Design - pierwsze kroki</a>
        header
    </header>
    <div id="main">
        <article>
            article<br>
            <?php echo $this->layout()->content; ?>
        </article>
        <nav>
            nav
        </nav>
        <aside>
            aside
        </aside>
    </div>
    <footer>footer</footer>
</body>
</html>